language: go
os: linux
sudo: required
services:
- docker
go:
- 1.11.x
go_import_path: github.com/inwinstack/ip-assigner
before_install:
- go get -u github.com/golang/dep/cmd/dep
script:
- make dep
- make
after_success:
- |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    # Log into Docker Hub.
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
    make build_image
    make push_image
  fi