apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-assigner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ip-assigner
  template:
    metadata:
      labels:
        k8s-app: ip-assigner
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: ip-assigner
      containers:
      - name: ip-assigner
        image: inwinstack/ip-assigner:v0.4.0
        args:
        - --v=2
        - --logtostderr=true
