apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-assigner
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-assigner
  template:
    metadata:
      labels:
        app: ip-assigner
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      serviceAccountName: ip-assigner
      containers:
      - name: ip-assigner
        image: inwinstack/ip-assigner:v0.3.0
        args:
        - --v=2
        - --logtostderr=true
        - --pool-name=default
        - --pool-addresses=192.168.99.10-192.168.99.100
        - --pool-ignore-namespaces=kube-system,default,kube-public,ingress-nginx